//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DegreeClock.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New York, NY")]
        public string LocationName {
            get {
                return ((string)(this["LocationName"]));
            }
            set {
                this["LocationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DayColor {
            get {
                return ((global::System.Drawing.Color)(this["DayColor"]));
            }
            set {
                this["DayColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color NightColor {
            get {
                return ((global::System.Drawing.Color)(this["NightColor"]));
            }
            set {
                this["NightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color TimePassedColor {
            get {
                return ((global::System.Drawing.Color)(this["TimePassedColor"]));
            }
            set {
                this["TimePassedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CurrentTimeLine {
            get {
                return ((global::System.Drawing.Color)(this["CurrentTimeLine"]));
            }
            set {
                this["CurrentTimeLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color FormBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["FormBackgroundColor"]));
            }
            set {
                this["FormBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color TimeTextColor {
            get {
                return ((global::System.Drawing.Color)(this["TimeTextColor"]));
            }
            set {
                this["TimeTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 10.8pt, style=Bold")]
        public global::System.Drawing.Font TimeTextFont {
            get {
                return ((global::System.Drawing.Font)(this["TimeTextFont"]));
            }
            set {
                this["TimeTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165, 165, 165")]
        public global::System.Drawing.Color DegreeNumbersColor {
            get {
                return ((global::System.Drawing.Color)(this["DegreeNumbersColor"]));
            }
            set {
                this["DegreeNumbersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 7pt")]
        public global::System.Drawing.Font DegreeNumbersFont {
            get {
                return ((global::System.Drawing.Font)(this["DegreeNumbersFont"]));
            }
            set {
                this["DegreeNumbersFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color DegreeLinesColor {
            get {
                return ((global::System.Drawing.Color)(this["DegreeLinesColor"]));
            }
            set {
                this["DegreeLinesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CurrentDegreeNumberColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentDegreeNumberColor"]));
            }
            set {
                this["CurrentDegreeNumberColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 7pt")]
        public global::System.Drawing.Font ClockNumbersFont {
            get {
                return ((global::System.Drawing.Font)(this["ClockNumbersFont"]));
            }
            set {
                this["ClockNumbersFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RosyBrown")]
        public global::System.Drawing.Color ClockNumbersColor {
            get {
                return ((global::System.Drawing.Color)(this["ClockNumbersColor"]));
            }
            set {
                this["ClockNumbersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RosyBrown")]
        public global::System.Drawing.Color ClockHoursColor {
            get {
                return ((global::System.Drawing.Color)(this["ClockHoursColor"]));
            }
            set {
                this["ClockHoursColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 7pt, style=Bold")]
        public global::System.Drawing.Font ClockHoursFont {
            get {
                return ((global::System.Drawing.Font)(this["ClockHoursFont"]));
            }
            set {
                this["ClockHoursFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedsUpgrade {
            get {
                return ((bool)(this["NeedsUpgrade"]));
            }
            set {
                this["NeedsUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDay {
            get {
                return ((bool)(this["ShowDay"]));
            }
            set {
                this["ShowDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNight {
            get {
                return ((bool)(this["ShowNight"]));
            }
            set {
                this["ShowNight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCurrentTimeMinutes {
            get {
                return ((bool)(this["ShowCurrentTimeMinutes"]));
            }
            set {
                this["ShowCurrentTimeMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCurrentTime {
            get {
                return ((bool)(this["ShowCurrentTime"]));
            }
            set {
                this["ShowCurrentTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCurrentTimeLine {
            get {
                return ((bool)(this["ShowCurrentTimeLine"]));
            }
            set {
                this["ShowCurrentTimeLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCurrentTimeFill {
            get {
                return ((bool)(this["ShowCurrentTimeFill"]));
            }
            set {
                this["ShowCurrentTimeFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRegTime {
            get {
                return ((bool)(this["ShowRegTime"]));
            }
            set {
                this["ShowRegTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDegTime {
            get {
                return ((bool)(this["ShowDegTime"]));
            }
            set {
                this["ShowDegTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDegreeNumbers {
            get {
                return ((bool)(this["ShowDegreeNumbers"]));
            }
            set {
                this["ShowDegreeNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWordsDegTime {
            get {
                return ((bool)(this["ShowWordsDegTime"]));
            }
            set {
                this["ShowWordsDegTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWordsRegTime {
            get {
                return ((bool)(this["ShowWordsRegTime"]));
            }
            set {
                this["ShowWordsRegTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DegTimeLong")]
        public global::DegreeClock.TimeNotation DegTimeLabelNotation {
            get {
                return ((global::DegreeClock.TimeNotation)(this["DegTimeLabelNotation"]));
            }
            set {
                this["DegTimeLabelNotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RegTime24Long")]
        public global::DegreeClock.TimeNotation RegTimeLabelNotation {
            get {
                return ((global::DegreeClock.TimeNotation)(this["RegTimeLabelNotation"]));
            }
            set {
                this["RegTimeLabelNotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DegTimeShort")]
        public global::DegreeClock.TimeNotation TitleBarNotation {
            get {
                return ((global::DegreeClock.TimeNotation)(this["TitleBarNotation"]));
            }
            set {
                this["TitleBarNotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTimeInTitleBar {
            get {
                return ((bool)(this["ShowTimeInTitleBar"]));
            }
            set {
                this["ShowTimeInTitleBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDegreeLines {
            get {
                return ((bool)(this["ShowDegreeLines"]));
            }
            set {
                this["ShowDegreeLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideWindowBorder {
            get {
                return ((bool)(this["HideWindowBorder"]));
            }
            set {
                this["HideWindowBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransparentBackground {
            get {
                return ((bool)(this["TransparentBackground"]));
            }
            set {
                this["TransparentBackground"] = value;
            }
        }
    }
}
